import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Loader } from "@googlemaps/js-api-loader";

const Home = (): any => {
  const { locales, asPath, locale }: any = useRouter();

  const [polylines, setPolylines]: any[] = useState([]);

  const flightPolylines: any[] = [];
  let flightPolylong: any[] = [];

  const loader = new Loader({
    apiKey: "AIzaSyDphTQDTDdGlXko8V-TfBRTmzZRsXrkhGA",
    libraries: ["drawing"],
  });

  const mapOptions = {
    center: {
      lat: 0,
      lng: 0,
    },
    zoom: 4,
  };

  loader
    .load()
    .then((google: any) => {
      let poly: google.maps.Polyline;
      let map: google.maps.Map;
      map = new google.maps.Map(document.getElementById("map") as HTMLElement, {
        zoom: 7,
        center: { lat: 30.0444, lng: 31.2357 },
      });

      const drawPolygon = (item: any[]) => {
        const polygon = new google.maps.Polygon({
          paths: item,
          strokeColor: "#000",
          strokeOpacity: 1,
          strokeWeight: 1,
          fillColor: "#FF0000",
          fillOpacity: 0.35,
        });
        polygon.setMap(map);
        poly.setMap(null);
      };

      map.addListener("click", (event: google.maps.MapMouseEvent) => {
        poly = new google.maps.Polyline({
          path: flightPolylines,
          geodesic: true,
          strokeColor: "#000000",
          strokeOpacity: 1.0,
          strokeWeight: 1,
        });

        poly.setMap(map);
        const path = poly.getPath();
        path.push(event.latLng);

        flightPolylines.push(event.latLng);
        // MARKERS
        flightPolylines.forEach((position: any, i: any) => {
          const marker = new google.maps.Marker({
            position,
            map,
            optimized: false,
          });

          // Add a click listener for each marker, and set up the info window.
          marker.addListener("click", (event: google.maps.MapMouseEvent) => {
            const first = flightPolylines[0];
            const result = flightPolylines.find(
              (path: any) => path === event.latLng
            );

            if (first == result) {
              flightPolylong = [...flightPolylines];
              drawPolygon(flightPolylines);
            } else {
              let currentIndex = flightPolylines.findIndex(
                (item: any) => item == result
              );
              // flightPolylines.splice(currentIndex, 1);
              console.log(currentIndex);
            }
          });
        });
      });
    })
    .catch((e) => {});

  useEffect(() => {}, []);

  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col-12">
          <div id="map" style={{ height: "100vh" }}></div>
        </div>
      </div>
    </div>
  );
};

export default Home;
